version: "3.7"

volumes:
  mongodb_container:
  app_container:

services:
  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_container:/data/db
    ports:
      - 27017:27017

  web:
    build: .
    command: flask --app search.py run
    volumes:
      - app_container:/home/app/webapp  
    ports:
      - "5000:5000"
    links:
      - mongodb_container
    depends_on:
      - mongodb_container
