version: "3.7"

volumes:
  mongodb_data_container:
  django_data_container:

services:
  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_data_container:/home/app/webapp  
    ports:
      - "8000:8000"
    links:
      - mongodb_container
    depends_on:
      - mongodb_container
